# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  docsupdate:
    cmds:
      - git submodule foreach git pull
      - git add docs .gitmodules
      - git commit -m "wiki update pulling"
      - git push
  default:
    cmds:
      - npm install
      - npm start
    silent: true
